server:
  port: 8010


#spring:
#  jpa:
#    generate-ddl: false
#    show-sql: true
#    hibernate:
#      ddl-auto: none
#  datasource:
#    platform: h2
#    schema: classpath:sql/schema.sql
#    data: classpath:sql/data.sql

logging:
  level:
    cn.harryai.microservicemovie.feign.UserFeignClient: debug
#  config: classpath:log/logback.xml
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://192.168.211.160:8762/eureka/,http://192.168.211.160:8761/eureka/}
spring:
  application:
    name: microservice-movie
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
  compression:
    request:
      enabled: true
      mime-types: texl/xml,application/xml,application/json
      min-request-size: 2048
  # 开启feign的 hystrix 支持
  hystrix:
      enabled: ture
    # 让代码配置优先级更高
#    default-to-properties: false
#指定名称feign的配置
#feign:
#  client:
#    config:
#      feignName:
        # 相当于Request.Options
#        connnectTimeout: 5000
        # 相当于Request.Options
#        readTimeout: 5000
        # 配置feign的日志级别，相当于代码配置的Logger
#        loggerLevel: full
        # 错误解码器，相当于代码配置方式中的ErrorDecoder
#        errorDecoder:
        # 配置重试，相当于代码中的Retryer
#        retryer:
        # 配置拦截器，相当于代码配置方式中的RequestInterceptor
#        requestInterceptors:
#          - com.ex
#          -
#        decode404: false

#feign通用配置
management:
  security:
    enabled: false